# Generated by Django 4.1.3 on 2023-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0002_appointmentbooking_in_person_staff_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='key',
            field=models.IntegerField(default=706600367555),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
