# Generated by Django 4.1.3 on 2023-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0003_appointmentbooking_accepted_appointmentbooking_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='key',
            field=models.IntegerField(verbose_name=694253618670),
        ),
    ]
