# Generated by Django 4.1.3 on 2023-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0010_staff_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
