# Generated by Django 4.1.3 on 2023-02-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0011_alter_staff_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
