# Generated by Django 4.1.3 on 2023-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0012_appointmentbooking_declined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='rearranged',
            field=models.BooleanField(default=False),
        ),
    ]
