# Generated by Django 4.1.3 on 2023-02-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0013_appointmentbooking_rearranged'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='user_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
